import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          background:
            "linear-gradient(100.61deg, rgba(253, 240, 233, 0.25) 1.4%, rgba(237, 105, 35, 0.125) 116.17%)",
        }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className="bg-black ">
          <Footer />
        </div>
      </body>
    </html>
  );
}
